# Site wide config:

title: "Some Abstract Algebra: a Primer and Interactive Workbook"
description: "by Richard Grassl and Tabitha Mingus"

footer: "&#169; Copyright 2019 Oscar Levin"

sass:
  style: compressed

theme: jekyll-theme-time-machine